name: Test

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: taiki-e/install-action@cargo-llvm-cov
    - uses: taiki-e/install-action@nextest
    - name: Run coverage
      run: cargo llvm-cov nextest --cobertura --output-path coverage.xml --profile ci
    - name: Code Coverage Summary Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage.xml
        output: file
    - name: Upload Test Report
      uses: actions/upload-artifact@v3
      if: always() 
      with:
        name: junit-test-results
        path: 'target/nextest/ci/junit.xml'
        retention-days: 1
    - name: Upload Coverage Report
      uses: actions/upload-artifact@v3
      if: always() 
      with:
        name: coverage-results
        path: 'coverage.xml'
        retention-days: 1
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3
      if: always() 
      with:
        report_paths: 'target/nextest/ci/junit.xml'
    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md
        
